name: Deploy website assets to S3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_region: ${{ secrets.TF_VAR_region }}
      TF_VAR_domain_name: ${{ secrets.TF_VAR_domain_name }}
      TF_VAR_hosted_zone: ${{ secrets.TF_VAR_hosted_zone }}
      TF_VAR_web_assets_bucket: ${{ secrets.TF_VAR_WEB_ASSETS_BUCKET }}
    
    outputs:
      cdn_id: ${{ steps.tf_output.outputs.cdn_id }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Configure AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform
      
      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: terraform

      - name: Terraform Apply
        id: tf
        run: terraform apply -auto-approve tfplan
        working-directory: terraform
      
      - name: Get CDN Distribution ID
        id: tf_output
        run: |
          export CDN_ID=$(terraform output -json cdn_distribution_id | jq -r '.')
          if [ -z "$CDN_ID" ]; then
            echo "CDN Distribution ID not found!" >&2
            exit 1
          fi
          echo "cdn_id=$CDN_ID" >> $GITHUB_OUTPUT
        working-directory: terraform
        
  deploy:
    needs: terraform
    runs-on: ubuntu-latest

    env:
      WEB_ASSETS_S3_BUCKET_NAME: ${{ vars.WEB_ASSETS_S3_BUCKET_NAME }}
    
    steps:
    - name: Confirm CloudFront Distribution ID
      run: |
        echo "CDN ID passed from previous job: ${{ needs.terraform.outputs.cdn_id }}"
    
    - name: Configure AWS credentials for S3 deployment
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Sync website to S3
      run: |
        aws s3 sync website/ s3://$WEB_ASSETS_S3_BUCKET_NAME  \
          --delete
    
    - name: Invalidate CloudFront Cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ needs.terraform.outputs.cdn_id }} \
          --paths "/*"